/* DO AN MON SE104 */
/* NHOM 16 */
/* THANH VIEN: MAI HIEU HIEN, BUI VAN THUAN, DANG THI TUONG VY */

CREATE DATABASE new_HOTEL;
USE new_HOTEL;

CREATE TABLE KHACHHANG
(
MAKH CHAR(6) PRIMARY KEY,
TENKH NVARCHAR(40),
DIACHI NVARCHAR(100),
GIOITINH NVARCHAR(5),
QUOCTICH NVARCHAR(40),
CCCD NVARCHAR(20),
SODT VARCHAR(15),
)

CREATE TABLE DICHVU
(
MADV CHAR(6) PRIMARY KEY,
TENDV CHAR(40),
DONGIA MONEY,
)

CREATE TABLE PHONG
(
MAPHONG CHAR(4) PRIMARY KEY,
LOAIPHONG CHAR(4) FOREIGN KEY REFERENCES LOAIPHONG(MALP),
TINHTRANG NVARCHAR(20),
)

CREATE TABLE LOAIPHONG
(
MALP CHAR(4) PRIMARY KEY,
TENLP NVARCHAR(40),
SONGUOI TINYINT,
THONGTIN NVARCHAR (300),
DONGIA MONEY,
)

CREATE TABLE HOADON
(
MAHD CHAR(8) PRIMARY KEY,
MAKH CHAR(6) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
MAPHONG CHAR(4) FOREIGN KEY REFERENCES PHONG(MAPHONG),
TINHTRANG NVARCHAR (20),
NGAYTHANHTOAN SMALLDATETIME,
TONG MONEY,
)

CREATE TABLE CTHOADON
(
MACTHD CHAR(10),
MAHD CHAR (8) FOREIGN KEY REFERENCES HOADON(MAHD),
NOIDUNG CHAR (6) FOREIGN KEY REFERENCES DICHVU(MADV),
SOLUONG TINYINT,
PRIMARY KEY (MACTHD, MAHD)
)

CREATE TABLE KHACHHANG_PHONG
(
MAKH_P CHAR(6) PRIMARY KEY,
MAKH CHAR(6) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
MAPHONG CHAR(4) FOREIGN KEY REFERENCES PHONG(MAPHONG),
NGAYTHUE SMALLDATETIME,
NGAYTRA SMALLDATETIME,
GIATHUE MONEY,
TINHTRANG NVARCHAR(20),
SONGUOI TINYINT,
)

CREATE TABLE THIETBI
(
MATB CHAR(4) PRIMARY KEY,
TENTB NVARCHAR(30),
GIATRI MONEY,
)

CREATE TABLE NHANVIEN
(
MANV CHAR(4) PRIMARY KEY,
TENNV NVARCHAR(40),
CCCD CHAR(20),
DIACHI NVARCHAR(100),
)

CREATE TABLE TAIKHOAN
(
MATK char(3) PRIMARY KEY,
MANV CHAR(4),
TENTK NVARCHAR(30),
MATKHAU NVARCHAR(30),
VAITRO NVARCHAR(30),
)

INSERT INTO TAIKHOAN VALUES('001', '001', 'admin', '123', 'Quản lý');
INSERT INTO TAIKHOAN VALUES('002', '001', 'tieptan', '123', 'Tiếp tân');
INSERT INTO NHANVIEN VALUES('001', 'Mai Hiếu Hiền', '01235678901', 'TPHCM');
INSERT INTO KHACHHANG_PHONG VALUES ('KP0003', 'KH0005', 'P101', '2022-06-15 14:55:00', '2022-06-17 14:55:00', 500000, 'Đang thuê', 2);

ALTER TABLE THIETBI
ALTER COLUMN TENTB NVARCHAR(200); 

ALTER TABLE CTHOADON
ADD THANHTIEN MONEY;

SELECT *
FROM HOADON
WHERE MAKH = 'KH0011' AND MAPHONG = 'P104' AND TINHTRANG = 'Dang thue';

SELECT *
FROM CTHOADON
WHERE MAHD = 'HD000001';

ALTER TABLE NHANVIEN
ADD SDT CHAR(10);

ALTER TABLE NHANVIEN
ADD CHUCVU NVARCHAR(50);

ALTER TABLE NHANVIEN
ADD LUONG MONEY;

ALTER TABLE NHANVIEN
ADD GIOITINH NVARCHAR(5);

ALTER TABLE TAIKHOAN
ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV); 

ALTER TABLE DICHVU
ALTER COLUMN TENDV NVARCHAR(40);